### ISSUE TITLE
File size limits in Chrome

### ISSUE THREAD

**Issue by josephrocca** [kayvr/token-hawk#2] opened 2023-05-19 22:05 UTC
Awesome project - I'm surprised at how fast it is based on your demo video! The initial message states:

> Due to file size limits in Chrome, use the 'Convert Model' button below in Firefox to split a 7B lamma.cpp GGML file into chunks. Then, in Chrome, you can load the resulting chunks using the 'Load Model' button ('Load Model' allows multiple file selection).

I'm wondering what the particular details of this Chrome problem are? In particular, I'm wondering if there's a crbug.com issue open for this? Happy to open one if there isn't, and if you can provide details.

Also, not sure if you're already using this, but IIRC the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) has different limits and performance characteristics compared to the usual `type="file"` input.

**Comment by kayvr** [comment] 2023-05-20 00:51
Thanks @josephrocca, I'm glad to hear you like the project.

This does appear to be a known chrome bug that was fixed a few days ago:

https://bugs.chromium.org/p/chromium/issues/detail?id=1444281

Once I verify that the fix works in chrome's testing channels, I'll put up a README banner. I'll also start rolling back the chunking in expectation of a fix. Thanks for opening the issue and linking the bug tracker as this bug wasn't on my radar.

Just as an experiment, I tried using the File System Access API you mentioned. But that didn't work around the issue.

For future reference, here's some details:

-------

When TokenHawk attempts to read past ~550MB, we get the following error:

```DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.```

The [FileReader](https://www.w3.org/TR/FileAPI/) API, webworkers with FileReaderSync, and using createObjectURL all failed.

Here are references to others running into file size limitations. The first reference is recent (2022), and mentions that firefox works while chrome doesn't:
* https://stackoverflow.com/questions/63376248/domexception-the-requested-file-could-not-be-read-typically-due-to-permission
* https://stackoverflow.com/questions/20706418/are-there-file-size-limitations-when-using-javascript-filereader-api
* https://stackoverflow.com/questions/28605393/size-limit-for-file-upload?noredirect=1&lq=1

**Comment by josephrocca** [comment] 2023-05-20 12:42
Hmm, yep - can reproduce. Seems like it has to do with maximum `ArrayBuffer` size:

https://load-file-test.glitch.me/

As you can see from that page, it fails if we stream in the file and then try to join the chunks into one big `ArrayBuffer` - so I'm guessing the `DOMException` error is downstream of the `ArrayBuffer` size limit stuff.

Would it be hard to adapt your code to stream in the chunks, and then maybe wrap the chunk array in a "virtual" reader or something like that? I guess you're already doing some form of chunking with your current approach to support Chrome, so hopefully it wouldn't be too hard to adapt.
```html
<input type="file" onchange="loadFileAsChunks(this.files[0])">
<script>
  async function loadFileAsChunks(file) {
    const reader = file.stream().getReader();
    const chunks = [];

    while(true) {
      const { done, value } = await reader.read();
      if(done) break;
      chunks.push(value);
    }

    return chunks; // an `Array` of `Uint8Array`s
  }
</script>
```

**Comment by kayvr** [comment] 2023-05-21 07:04
Alright, I tested the latest Canary and the problem is fixed with the code as-is. My plan is to rollback all of the chunking work and expose the option to load a GGML model directly. I'll look at implementing this tomorrow or Monday.

Secondarily, I'm going to look into your streaming solution this week. Since maximum ArrayBuffer size appears to be the issue, that makes me wonder the size of the ArrayBuffers being allocated with my current method. We don't really need to allocate more than 500mb at a time for 7B models. As we grow the model sizes, streaming might be a better option in the long-run.

**Comment by kayvr** [comment] 2023-05-23 17:16
There's now a new version of TokenHawk that loads GGML model files directly. I've also updated the UI to indicate what version of Chrome Canary is required.

Honestly, model loading is slower than I would like. I'll look into @josephrocca's streaming suggestion as a possible solution.

I have only tested this on Windows, and I'm going to leave this open until I get a chance to test on Ubuntu.

**Comment by josephrocca** [comment] 2023-05-23 21:55
Regarding my earlier suggestion to try the new File System Access API, it might be worth looking into the high-performance stuff that they've even more recently added to that API:

> The origin private file system provides optional access to a special kind of file that is highly optimized for performance, for example, by offering in-place and exclusive write access to a file's content. In Chromium 102 and later, there is an additional method on the origin private file system for simplifying file access: createSyncAccessHandle() (for synchronous read and write operations). It is exposed on FileSystemFileHandle, but exclusively in [Web Workers](https://developer.mozilla.org/docs/Web/API/Web_Workers_API/Using_web_workers).

https://developer.chrome.com/articles/file-system-access/#accessing-files-optimized-for-performance-from-the-origin-private-file-system

My understanding is that the File System Access API allows you to access files from the users computer, and also from the [Origin Private File System](https://developer.chrome.com/articles/origin-private-file-system/), which is like a kind of site/origin-specific "local storage" where you can put huge files (`localStorage` and `IndexedDB` only allows a small amount of data to be stored in comparison), but you can read/write to/from the Origin Private File System faster that to/from the files on the user's compute, so it might be possible to load a file from the user's computer into OPFS in a single command with native performance, and then use the fast sync access handle mentioned above. Also, I think OPFS can be used for caching too?

But this is just a guess - figured I'd mention this just to give you a heads up in case you hadn't heard of OPFS.

**Comment by kayvr** [comment] 2023-06-14 20:59
Thanks again for your help! I just verified that TokenHawk works across Windows, Linux, and macOS in chrome latest. No more canary.

Closing this out.

**Closed as completed by kayvr** 2023-06-14 20:59 UTC
